services:
  jupyter:
    build: .
    image: nocluster_spark_3.5.1
    container_name: jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/opt/spark-notebooks
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
      - SPARK_UI_PORT=4040
